// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU3MeENpLO7EHtXdO9rH5IfJcAUxvL3Is',
    appId: '1:549248437301:web:343f3587f8f541f19d357c',
    messagingSenderId: '549248437301',
    projectId: 'shopping-list-10a41',
    authDomain: 'shopping-list-10a41.firebaseapp.com',
    storageBucket: 'shopping-list-10a41.appspot.com',
    measurementId: 'G-7075PNYVQ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkt4gBmZz9OoMfcYmU2AsbuEFztMU_MWQ',
    appId: '1:549248437301:android:1415e11a009afb7c9d357c',
    messagingSenderId: '549248437301',
    projectId: 'shopping-list-10a41',
    storageBucket: 'shopping-list-10a41.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxmXnmNtsa7PmZfuUDp11CBJU84CFy2l4',
    appId: '1:549248437301:ios:fb6793d7e2a43d389d357c',
    messagingSenderId: '549248437301',
    projectId: 'shopping-list-10a41',
    storageBucket: 'shopping-list-10a41.appspot.com',
    iosBundleId: 'com.example.shoppingList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxmXnmNtsa7PmZfuUDp11CBJU84CFy2l4',
    appId: '1:549248437301:ios:fb6793d7e2a43d389d357c',
    messagingSenderId: '549248437301',
    projectId: 'shopping-list-10a41',
    storageBucket: 'shopping-list-10a41.appspot.com',
    iosBundleId: 'com.example.shoppingList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBU3MeENpLO7EHtXdO9rH5IfJcAUxvL3Is',
    appId: '1:549248437301:web:a4efda5f4882ed389d357c',
    messagingSenderId: '549248437301',
    projectId: 'shopping-list-10a41',
    authDomain: 'shopping-list-10a41.firebaseapp.com',
    storageBucket: 'shopping-list-10a41.appspot.com',
    measurementId: 'G-BGGZYLBZ9M',
  );

}